exchange_rates.settings:
  type: config_object
  label: 'Exchange Rates settings'
  mapping:
    base_currency:
      type: string
      label: 'Base Currency'
    conversion_currency:
      type: sequence
      label: 'Conversion Currencies'
      sequence:
        type: string
        label: "Conversion Currency"
    currency:
      type: sequence
      label: "Currency"
      sequence:
        type: exchange_rates.currency.[%key]

exchange_rates.currency.*:
  type: string
